# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: webscrutinizer 0.0.1.pre ruby lib

Gem::Specification.new do |s|
  s.name = "webscrutinizer"
  s.version = "0.0.1.pre"

  s.required_rubygems_version = Gem::Requirement.new("> 1.3.1") if s.respond_to? :required_rubygems_version=
  s.require_paths = ["lib"]
  s.authors = ["Marcel Massana"]
  s.date = "2014-04-09"
  s.description = "An unorthodox framework to recursively spider websites, parse and collect text data"
  s.email = "xaxaupua@gmail.com"
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.rdoc"
  ]
  s.files = [
    ".document",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "README.rdoc",
    "Rakefile",
    "examples/ajbcn/ajbcn.rb",
    "examples/ajbcn/setup.rb",
    "examples/gencat/gencat.rb",
    "examples/gencat/setup.rb",
    "examples/gisa/gisa.rb",
    "examples/gisa/setup.rb",
    "gem_graph.png",
    "lib/webscrutinizer.rb",
    "lib/webscrutinizer/data_dump.rb",
    "lib/webscrutinizer/error.rb",
    "lib/webscrutinizer/helpers.rb",
    "lib/webscrutinizer/level.rb",
    "lib/webscrutinizer/printlog.rb",
    "lib/webscrutinizer/queue.rb",
    "lib/webscrutinizer/report.rb",
    "lib/webscrutinizer/seed_pool.rb",
    "lib/webscrutinizer/simple_map.rb",
    "lib/webscrutinizer/threaded_agent.rb",
    "lib/webscrutinizer/version.rb",
    "test/helper.rb",
    "test/template_test_webscrutinizer.rb",
    "test/test_data_dump.rb",
    "test/test_level.rb",
    "test/test_seed_pool.rb",
    "webscrutinizer.gemspec"
  ]
  s.homepage = "http://github.com/syborg/webscrutinizer"
  s.licenses = ["MIT"]
  s.rubygems_version = "2.2.1"
  s.summary = "scrutinizing the web ..."

  if s.respond_to? :specification_version then
    s.specification_version = 4

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<mme_tools>, ["~> 0.0.4"])
      s.add_runtime_dependency(%q<web_dump>, ["~> 0.0.2.0"])
      s.add_runtime_dependency(%q<mechanize>, ["~> 2.7.3"])
      s.add_runtime_dependency(%q<ya2yaml>, ["~> 0.30"])
      s.add_runtime_dependency(%q<yajl-ruby>, [">= 0"])
      s.add_development_dependency(%q<bundler>, ["~> 1.6.1"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.6.4"])
      s.add_development_dependency(%q<simplecov>, [">= 0"])
      s.add_development_dependency(%q<fakeweb>, ["~> 1.3.0"])
      s.add_development_dependency(%q<minitest>, [">= 5.0.0"])
    else
      s.add_dependency(%q<mme_tools>, ["~> 0.0.4"])
      s.add_dependency(%q<web_dump>, ["~> 0.0.2.0"])
      s.add_dependency(%q<mechanize>, ["~> 2.7.3"])
      s.add_dependency(%q<ya2yaml>, ["~> 0.30"])
      s.add_dependency(%q<yajl-ruby>, [">= 0"])
      s.add_dependency(%q<bundler>, ["~> 1.6.1"])
      s.add_dependency(%q<jeweler>, ["~> 1.6.4"])
      s.add_dependency(%q<simplecov>, [">= 0"])
      s.add_dependency(%q<fakeweb>, ["~> 1.3.0"])
      s.add_dependency(%q<minitest>, [">= 5.0.0"])
    end
  else
    s.add_dependency(%q<mme_tools>, ["~> 0.0.4"])
    s.add_dependency(%q<web_dump>, ["~> 0.0.2.0"])
    s.add_dependency(%q<mechanize>, ["~> 2.7.3"])
    s.add_dependency(%q<ya2yaml>, ["~> 0.30"])
    s.add_dependency(%q<yajl-ruby>, [">= 0"])
    s.add_dependency(%q<bundler>, ["~> 1.6.1"])
    s.add_dependency(%q<jeweler>, ["~> 1.6.4"])
    s.add_dependency(%q<simplecov>, [">= 0"])
    s.add_dependency(%q<fakeweb>, ["~> 1.3.0"])
    s.add_dependency(%q<minitest>, [">= 5.0.0"])
  end
end

