--- !ruby/object:SimpleMap 
current_value: 
data: 
  "Organisme:": :ORGANISME
  "Plec de cl\xC3\xA0usules administratives": :PLEC_ADM
  plec administratiu: :PLEC_ADM
  "Tipus de contracte:": :TIPUS_CONTR
  "FAX:": :FAX
  "Objecte del contracte:": :OBJECTE
  "plec de prescripcions t\xC3\xA8cniques": :PLEC_TEC
  "plec cl\xC3\xA0usules administratives partic.": :PLEC_ADM
  "Import IVA:": :PRESSUPOST_IVA
  "Data de publicaci\xC3\xB3:": :DATA_PUBL
  "Procediment:": :PROCEDIMENT
  Plecs Tecniques: :PLEC_TEC
  "Data l\xC3\xADmit presentaci\xC3\xB3 ofertes:": :DATA_PRES
  "data publicaci\xC3\xB3:": :DATA_PUBL
  "Data de formalitzaci\xC3\xB3": :DATA_FORM
  "DATA DE FORMALITZACI\xC3\x93": :DATA_FORM
  "Tipus:": :TIPUS
  "plec t\xC3\xA8cnic": :PLEC_TEC
  "Tramitaci\xC3\xB3:": :TRAMITACIO
  "Codi contracte:": :EXP
  "Municipi:": :LLOC
  "Import Garantia Provisional:": :GARANTIA
  "Pressupost net:": :PRESSUPOST_NET
  "Pressupost base de licitaci\xC3\xB3:": :PRESSUPOST_BASE
  "Objecte:": :OBJECTE
  "Import Base:": :PRESSUPOST_BASE
  "Data l\xC3\xADmit de presentaci\xC3\xB3 d'ofertes:": :DATA_PRES
  "Data d'adjudicaci\xC3\xB3:": :DATA_ADJU
  "Plec t\xC3\xA8cnic": :PLEC_TEC
  "Observacions:": :OBSERVACIONS
  "Diari oficial:": :DOF
  "N\xC3\xBAmero del contracte:": :NUMERO
  "Data de formalitzaci\xC3\xB3:": :DATA_FORM
  "Criteris de valoraci\xC3\xB3": :CRITERIS
  Plec Administratiu: :PLEC_ADM
  "Ordenant:": :ORDENANT
  "Forma Adjudicaci\xC3\xB3:": :FORMA_ADJUD
  "Import Total:": :"PRESSUPOST_+IVA"
  "DATA DE FORMALITZACI\xC3\x93 DEL CONTRACTE": :DATA_FORM
  "ADJUDICACI\xC3\x93": :ADJUDICACIO
  "Import de l'IVA:": :PRESSUPOST_IVA
  "Adjudicatari:": :ADJUDICATARI
  "Data de formalitzaci\xC3\xB3 del contracte": :DATA_FORM
  "Tel\xC3\xA8fon:": :TEL
unmapped_keys: 
- "N\xC3\xBAmero d'Anunci:"
- "Data estimada d'inici:"
- Anunci DOUE
- "Criteris de valoraci\xC3\xB3:"
- "Mitj\xC3\xA0 i data de remissi\xC3\xB3/publicaci\xC3\xB3 de la licitaci\xC3\xB3:"
- "Classificaci\xC3\xB3/Solvencia:"
- "Condicions especials d'execuci\xC3\xB3:"
- ANNEX 2
- "Divisi\xC3\xB3 per:"
- "data tramesa:"
- "Pr\xC3\xB2rroga:"
- "Valor estimat:"
- "Garant\xC3\xADa definitiva:"
- Annexos
- Plec administratiu
- "Quadre de caracter\xC3\xADstiques"
- 11000038 - RECTIFICACIO CLASSIF. EMPRESA
- 05.07.2011 - ANUNCI BOPB - rectif.classi
- annex 1
- PLEC CLAUSULES ADMVES
- annex 2
- ANUNCI BOPB - 07.07.2011
- "PLEC CONDICIONS TECNIQUES I PROJ. B\xC3\x80SIC"
- "PLEC CL\xC3\x80USULES ADMINISTRATIVES"
- ANNEX 1
- PLEC ADMINISTRATIU
- ANNEX 2 PRESSUPOST
- PLEC TECNIC
- "1486-Plec de cl\xC3\xA0usules particulars"
- "Resoluci\xC3\xB3 d'aprovaci\xC3\xB3 de la licitaci\xC3\xB3"
- "1486-Plec de Prescripcions T\xC3\xA8cniques"
- anunci
- "Plec Administratiu i T\xC3\xA8cnic"
- "ANNEX 1 PLEC T\xC3\x88CNIC"
- "PLEC DE CL\xC3\x80USULES ADMINISTRATIVES"
- "Annex Plec T\xC3\xA8cnic 2"
- "PLEC DE PRESCRIPCIONS T\xC3\x88CNIQUES"
- "Annex Plec T\xC3\xA8cnic 1"
- PLEC DE CLAUSULES ADMINISTRATIVES
- "Decret autoritzaci\xC3\xB3 despesa"
- Model oferta
- "Annex descripci\xC3\xB3 nivells LOPD"
- Annex requeriments funcionals
- "Annex est\xC3\xA0ndards desenv.i metodologia"
- "Plec t\xC3\xA8cnic II"
- "Plec t\xC3\xA8cnic I"
- "Plec t\xC3\xA8cnic III"
- "Adjudicaci\xC3\xB3 provisional"
- "Preu del contracte:"
- "Decret d'adjudicaci\xC3\xB3"
- ACTA 3
- "DECRET ADJUDICACI\xC3\x93"
- "Termini per formalitzar:"
- Dades certificades amb Segell de Temps
- ACTA 4
- "Resoluci\xC3\xB3 adjudicaci\xC3\xB3"
- DILIGENCIA FORMALITZACIO CONTRACTE
- "dilig\xC3\xA8ncia formalitzaci\xC3\xB3 contracte"
- "20112102 FORMALITZACI\xC3\x93 CONTRACTE"
- "FORMALITZACI\xC3\x93 DEL CONTRACTE"
- "DILIG\xC3\x88NCIA DE FORMALITZACI\xC3\x93"
- "anunci formalitzaci\xC3\xB3"
- "Import de licitaci\xC3\xB3:"
